; ESP32-C3 Super Mini + 0.42" OLED (72x40, SSD1306, SDA=5 SCL=6)
[platformio]
src_dir = .

[env:ext-box]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
upload_port = COM5
board_build.flash_mode = dio
build_flags =
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
  adafruit/Adafruit PWM Servo Driver Library
  olikraus/U8g2
lib_ldf_mode = deep+
